# Generated by Django 5.1.4 on 2024-12-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reportres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RescueForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(help_text='Enter your 10-digit mobile number', max_length=10, unique=True)),
                ('rescue_forces', models.CharField(choices=[('fire', 'Fire and Rescue Services'), ('police', 'Police'), ('coast_guard', 'Coast Guard'), ('ndrf', 'NDRF'), ('volunteer', 'Volunteer'), ('sdma', 'SDMA'), ('healthcare', 'HEALTHCARE & MEDICAL SERVICE'), ('trauma', 'TRAUMA CARE')], help_text='Select your rescue force', max_length=50)),
                ('location', models.CharField(help_text='Enter your location', max_length=255)),
                ('district', models.CharField(choices=[('tvm', 'Thiruvananthapuram'), ('kollam', 'Kollam'), ('pta', 'Pathanamthitta'), ('alpy', 'Alappuzha'), ('kottayam', 'Kottayam'), ('ekm', 'Ernakulam'), ('tcr', 'Thrissur'), ('pkd', 'Palakkad'), ('mlp', 'Malappuram'), ('kkd', 'Kozhikode'), ('wnd', 'Wayanad'), ('knr', 'Kannur'), ('ksd', 'Kasaragod')], help_text='Select your district', max_length=50)),
                ('pincode', models.CharField(help_text='Enter your 6-digit pincode', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Updateoprres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('mobile_no', models.CharField(help_text='Enter your 10-digit mobile number', max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(help_text='Enter your address')),
                ('dob', models.DateField(help_text='Enter your date of birth (YYYY-MM-DD)')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('district', models.CharField(choices=[('tvm', 'Thiruvananthapuram'), ('kollam', 'Kollam'), ('pta', 'Pathanamthitta'), ('alpy', 'Alappuzha'), ('kottayam', 'Kottayam'), ('ekm', 'Ernakulam'), ('tcr', 'Thrissur'), ('pkd', 'Palakkad'), ('mlp', 'Malappuram'), ('kkd', 'Kozhikode'), ('wnd', 'Wayanad'), ('knr', 'Kannur'), ('ksd', 'Kasaragod')], help_text='Select your district', max_length=50)),
                ('pincode', models.CharField(help_text='Enter your 6-digit pincode', max_length=6)),
                ('relative_contact', models.CharField(help_text="Enter relative's 10-digit contact number", max_length=10)),
                ('password', models.CharField(help_text='Enter your password', max_length=128)),
            ],
        ),
    ]
