# Generated by Django 5.1.4 on 2024-12-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaintres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
