# Generated by Django 5.1.4 on 2025-01-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0002_complaintres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(help_text='Enter your address', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(choices=[('tvm', 'Thiruvananthapuram'), ('kollam', 'Kollam'), ('pta', 'Pathanamthitta'), ('alpy', 'Alappuzha'), ('kottayam', 'Kottayam'), ('ekm', 'Ernakulam'), ('tcr', 'Thrissur'), ('pkd', 'Palakkad'), ('mlp', 'Malappuram'), ('kkd', 'Kozhikode'), ('wnd', 'Wayanad'), ('knr', 'Kannur'), ('ksd', 'Kasaragod')], help_text='Select your district', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(help_text='Enter your date of birth (YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(help_text='Enter your 6-digit pincode', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='relative_contact',
            field=models.CharField(help_text="Enter relative's 10-digit contact number", max_length=10, null=True),
        ),
    ]
