# Generated by Django 5.1.4 on 2025-01-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0004_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('situation', models.CharField(max_length=255, verbose_name='Situation')),
                ('message', models.TextField(verbose_name='Message')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
