# Generated by Django 5.1.4 on 2025-01-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0006_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='district',
            field=models.CharField(choices=[('TVM', 'Thiruvananthapuram'), ('KLM', 'Kollam'), ('PTA', 'Pathanamthitta'), ('ALP', 'Alappuzha'), ('KTM', 'Kottayam'), ('IDK', 'Idukki'), ('EKM', 'Ernakulam'), ('TSR', 'Thrissur'), ('PKD', 'Palakkad'), ('MLP', 'Malappuram'), ('KKD', 'Kozhikode'), ('WYD', 'Wayanad'), ('KNR', 'Kannur'), ('KSG', 'Kasaragod')], max_length=25),
        ),
    ]
