# Generated by Django 5.1.4 on 2025-01-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0008_rescue_assigntab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Updateoprres',
        ),
    ]
