# Generated by Django 5.1.4 on 2025-01-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0010_updateoprres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
