# Generated by Django 5.1.4 on 2025-01-09 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0015_delete_assigntab'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigntab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('rescuelocation', models.CharField(max_length=255)),
                ('message', models.TextField(verbose_name='Message')),
                ('rescue_force', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reksha.rescue')),
            ],
        ),
    ]
