# Generated by Django 5.1.4 on 2025-01-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0016_assigntab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assigntab',
        ),
        migrations.DeleteModel(
            name='Rescue',
        ),
    ]
