# Generated by Django 5.1.4 on 2025-01-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0020_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
