# Generated by Django 5.1.4 on 2025-01-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0021_alter_notification_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
