# Generated by Django 5.1.4 on 2025-01-11 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0023_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
