# Generated by Django 5.1.4 on 2025-01-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0025_rescue_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rescue',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
