# Generated by Django 5.1.4 on 2025-01-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0027_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assigntab',
        ),
    ]
