# Generated by Django 5.1.4 on 2025-01-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0029_assigntab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Updateoprres',
        ),
    ]
