# Generated by Django 5.1.4 on 2025-01-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0031_updateoprres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assigntab',
        ),
    ]
