# Generated by Django 5.1.4 on 2025-01-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0032_delete_assigntab'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigntab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victimuser', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('rescue_force', models.CharField(max_length=30)),
                ('landmark', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
