# Generated by Django 5.1.4 on 2025-01-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0033_assigntab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Updateoprres',
        ),
    ]
