# Generated by Django 5.1.4 on 2025-01-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0034_delete_updateoprres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updateoprres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workid', models.TextField()),
                ('victimname', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
