# Generated by Django 5.1.4 on 2025-01-27 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0036_commonfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
