# Generated by Django 5.1.4 on 2025-01-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0037_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('district', models.CharField(choices=[('TVM', 'Thiruvananthapuram'), ('KLM', 'Kollam'), ('PTA', 'Pathanamthitta'), ('ALP', 'Alappuzha'), ('KTM', 'Kottayam'), ('IDK', 'Idukki'), ('EKM', 'Ernakulam'), ('TSR', 'Thrissur'), ('PKD', 'Palakkad'), ('MLP', 'Malappuram'), ('KKD', 'Kozhikode'), ('WYD', 'Wayanad'), ('KNR', 'Kannur'), ('KSG', 'Kasaragod')], max_length=25)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('email_id', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
