# Generated by Django 5.1.4 on 2025-01-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0038_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
