# Generated by Django 5.1.4 on 2025-01-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0041_replyuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
