# Generated by Django 5.1.4 on 2025-02-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0044_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
