# Generated by Django 5.1.4 on 2025-02-03 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0045_delete_otpverification_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('mobile_no', models.CharField(help_text='Enter your 10-digit mobile number', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(help_text='Enter your address', null=True)),
                ('dob', models.DateField(help_text='Enter your date of birth (YYYY-MM-DD)', null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('district', models.CharField(choices=[('tvm', 'Thiruvananthapuram'), ('kollam', 'Kollam'), ('pta', 'Pathanamthitta'), ('alpy', 'Alappuzha'), ('kottayam', 'Kottayam'), ('ekm', 'Ernakulam'), ('tcr', 'Thrissur'), ('pkd', 'Palakkad'), ('mlp', 'Malappuram'), ('kkd', 'Kozhikode'), ('wnd', 'Wayanad'), ('knr', 'Kannur'), ('ksd', 'Kasaragod')], help_text='Select your district', max_length=50, null=True)),
                ('pincode', models.CharField(help_text='Enter your 6-digit pincode', max_length=6, null=True)),
                ('relative_contact', models.CharField(help_text="Enter relative's 10-digit contact number", max_length=10, null=True)),
                ('password', models.CharField(help_text='Enter your password', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reksha.userprofile')),
            ],
        ),
    ]
