# Generated by Django 5.1.4 on 2025-02-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0046_userprofile_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendrepuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
