# Generated by Django 5.1.4 on 2025-02-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0048_sendrepres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='replyuser',
        ),
    ]
