# Generated by Django 5.1.4 on 2025-02-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0049_delete_replyuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reportres',
        ),
    ]
