# Generated by Django 5.1.4 on 2025-02-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0050_delete_reportres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
