# Generated by Django 5.1.4 on 2025-03-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reksha', '0051_reportres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authentication',
        ),
    ]
